#+BEGIN_COMMENT
.. title: 房子，北京
.. slug: house-beijing-2017-03-15
.. date: 2017-03-15 19:26:52 UTC+08:00
.. tags: House, Life
.. category: LIFE
.. link: 
.. description: 
.. type: text
#+END_COMMENT


* 缘起
今天早上看了一篇同学分享的文章--[[http://mp.weixin.qq.com/s?__biz=MjM5OTQ0MjM4MA==&mid=2651896417&idx=2&sn=3f956b783256b99e925c1c062b50a773&chksm=bcdf78c28ba8f1d416901eae3e4cea7230f176c975007d4af61c153303ecc75a498ce7711a31&mpshare=1&scene=1&srcid=0313S3DzfdNKeRHFAUfjBRoZ#rd][《清华硕士集体逃离北京！一枚中科院科研人员的自白： 我为什么选择离开》]]

又一次被现实刺痛，思绪满天飞，于是写下这篇博客

{{{TEASER_END}}}

* 男怕入错行

细细想来，在北京已经待了十年有余，八年的求学生涯加近两年的工作，占去了我人生黄金年龄的 1/3，对未来的规划越来越清晰，失去了很多东西，也收获了很多东西。

“男怕入错行”，四五年前，还不以为然，年少轻狂的我坚持认为，只要我想做，我想坚持，“行行出状元”，然而，现实给了我一个大大的火锅。

我博士是做基础研究的，上学第二三年，当时就想想一辈子就去做基础研究，感觉挺适合我的，可以让我静下心来，做自己感兴趣的事情。前年毕业时，我最终选择了去公司，一部分原因是在实验室的生活太苦闷，研究课题都是老板定的，自己的想法没有一个实现的，当然了，发的文章分也不高，好的科研院所比较难进(基本只招北京本地人了)，博后也不想去；另一个方面原因就是因为 money，科研赚的太少了，男人，还是要养家糊口的，现在，我的目标越来越清晰，以后就是医学数据科学家这个方向，不会有大的改动。

科研不像现在 IT 互联网方向的，动不动本科硕士毕业就二三十万，我们博士毕业两三年也到不了这个数。所以，我需要做出改变，不过，改变的难度也是比较大的，但是，不改变，未来会一直苦下去。

现在，才算真正理解了“男怕入错行”这句话。

* 努力前行

在北京生活，房子是一个绕不开的话题，像我这种家在农村比较贫穷的情况，很难买的起房，学区房，算了吧，能在北京周边买一个小房子已经谢天谢地了，不过，还好，我有爱人陪伴，不离不弃，这是我来北京最大的收获。

为了未来的生活，为了未来有一套我们的爱巢，我要努力前行。
* Creative Commons licensing
#+BEGIN_QUOTE
TITLE: 房子，北京\\
AUTHOR: lengyueyang \\
DATE: 2017-03-15 19:26:52 UTC+08:00\\
UPDATED: \\
LICENSE: The blog is licensed under a [[http://creativecommons.org/licenses/by-sa/4.0/][Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License]], commercial use is not allowed, for any reprint, please indicate address and signature.
https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png
#+END_QUOTE
